const ParticipationSection = () => {
  return (
    <section id="participation-details">
      <h2 className="font-lora">What Participation Involves</h2>
      <ul>
        <li>
          <strong>Task:</strong> You will be presented with instructions and pairs of text responses generated by AI.
          Your primary task is to choose the response you prefer and rate your confidence or preference. You may also
          provide optional comments.
        </li>
        <li>
          <strong>Time Commitment:</strong> Participation typically takes between 10 to 45 minutes, depending on the
          number of entries you evaluate.
        </li>
        <li>
          <strong>Voluntary Nature:</strong> Your participation is completely voluntary. You can choose to stop at any
          time without giving a reason and without any penalty. Closing the browser window will end your session.
        </li>
        <li>
          <strong>Withdrawal:</strong> You can withdraw your participation at any point. Data collected up to the point
          of withdrawal may be retained and used anonymously.
        </li>
      </ul>
    </section>
  );
};

export default ParticipationSection;
