const ParticipationSection = () => {
  return (
    <section id="participation">
      <h2 className="font-lora">3. Nature of Participation</h2>
      <p>
        Participation in this Study is entirely voluntary. You will be asked to review pairs of text generated by AI
        models and select your preference, provide a rating, and optionally offer comments. The estimated time
        commitment is between 10 to 45 minutes, depending on the number of entries you choose to evaluate.
      </p>
      <p>
        You are free to withdraw from the Study at any time without penalty by simply closing your browser window or
        navigating away from the survey pages. Any data submitted up to the point of withdrawal may be retained and used
        anonymously for research purposes as outlined in these Terms.
      </p>
    </section>
  );
};

export default ParticipationSection;
